using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using TreeEditor.Domain.Entities;

namespace TreeEditor.Infrastructure.Persistence.Configurations;

public sealed class ElementConfiguration : IEntityTypeConfiguration<Element>
{
    public void Configure(EntityTypeBuilder<Element> builder)
    {
        builder.ToTable("elements");
        builder.HasKey(e => e.Id);

        // GENERATED BY DEFAULT lets the seeder insert deterministic ids while still
        // auto-generating ids for normal inserts.
        builder.Property(e => e.Id).HasColumnName("id").UseIdentityByDefaultColumn();
        builder.Property(e => e.Value).HasColumnName("value").IsRequired();
        builder.Property(e => e.ParentId).HasColumnName("parent_id");
        builder.Property(e => e.IsDeleted).HasColumnName("is_deleted").HasDefaultValue(false);
        builder.Property(e => e.Version).HasColumnName("version").HasDefaultValue(1L);
        builder.Property(e => e.CreatedAt).HasColumnName("created_at");
        builder.Property(e => e.UpdatedAt).HasColumnName("updated_at");

        builder.HasIndex(e => e.ParentId).HasDatabaseName("ix_elements_parent_id");

        // Self reference. Restrict avoids EF trying to cascade/handle the polymorphic tree;
        // subtree deletion is done explicitly with a recursive CTE.
        builder.HasOne(e => e.Parent)
            .WithMany(e => e.Children)
            .HasForeignKey(e => e.ParentId)
            .OnDelete(DeleteBehavior.Restrict);

        // Soft-deleted rows are invisible to every ordinary query.
        builder.HasQueryFilter(e => !e.IsDeleted);
    }
}
